[tool.poetry]
name = "ncs-task"
version = "0.1.0"
description = ""
authors = ["Harsh Mishra <hmisraji07@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
